# Generated by Django 4.2 on 2023-04-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animade', '0005_rename_createddesigns_createddesign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createddesign',
            name='image',
            field=models.ImageField(default=None, max_length=1000, upload_to='designs/'),
        ),
    ]
