# Generated by Django 4.2 on 2023-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animade', '0006_alter_createddesign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_status',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Unlimited', 'Unlimited')], default='Free', max_length=10),
        ),
    ]
